### ISSUE TITLE
WGSL compile module error

### ISSUE THREAD

**Issue by termuxinator** [pjhusky/pocketpt-webgpu#1]
branch: main
file: pocketpt_webgpu_wgsl_one_file.html

Did not work for me so i added code to check module compile status.
(via getCompilationInfo)
The reported errors were about dereferencing pointers to u32.

fn intersect(ray: Ray, hitInfo: ptr<function, HitInfo>)

To fix i have changed lines of:
*(hitInfo).objType = eSphere;
*(hitInfo).objIdx = i;
*(hitInfo).rayT = t;

Into:
(*hitInfo).objType = eSphere;
(*hitInfo).objIdx = i;
(*hitInfo).rayT = t;

Now it runs without errors.

BTW im on mobile Android Chrome browser.

**Comment by pjhusky** [comment]
Well spotted, thanks a lot for the fix!
